name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia
  workflow_dispatch:     # botão "Run workflow"

permissions:
  contents: write   # PERMISSÃO PRA FAZER PUSH

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AnaLuiza-DaNova
          outputs: dist/snake.svg

      - name: Commit and push snake.svg
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake"
          branch: output
          file_pattern: dist/snake.svg
