name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Gera a cobrinha num diretório temporário (/tmp/snake)
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AnaLuiza-DaNova
          outputs: /tmp/snake.svg

      # 2. Checkout da branch output
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output

      # 3. Copia o snake.svg gerado do /tmp para o repo
      - name: Move generated file
        run: |
          mkdir -p dist
          cp /tmp/snake.svg dist/snake.svg

      # 4. Commit
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake"
          branch: output
          file_pattern: dist/snake.svg
